# Konfigurasi Telegram Bot untuk notifikasi error & aktivitas penting
# Isi bot_token dan chat_id sesuai bot yang sudah dibuat

telegram.enabled=true
telegram.bot_token=8757941036:AAH7XFd9zoRwvI0cLjX08NAjz5OCiotNk9Q
# Untuk multiple penerima, pisahkan dengan koma. Contoh: 918804404,123456789
telegram.chat_id=918804404
telegram.rs_name=RSPH
